name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        check-latest: true
        java-version: 19
    - name: Build
      run: |
        git clone --depth=1 -q https://github.com/ymcx/radon
        cd radon
        (new-object System.Net.WebClient).DownloadFile("https://dl.google.com/android/repository/build-tools_r33-windows.zip","$pwd\a.zip")
        tar xf a.zip
        Invoke-Expression (curl -s https://docs.gradle.org/nightly/release-notes.html | % {$_.replace("<p><code>","").replace("</code></p>","")} | Select-String "gradlew wrapper --gradle-version=")
        .\gradlew.bat -q assembleRelease
        .\android-*\zipalign.exe 4 app\build\outputs\apk\release\app-release-unsigned.apk a.apk
        .\android-*\apksigner.bat sign --ks-key-alias keystore --ks-pass pass:keystore --ks .github\workflows\keystore.jks a.apk   
        curl bashupload.com -s -T a.apk
