name: Build APK
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 19
    - name: Build APK
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: |
        mkdir -p app/keystore
        sudo apt install apksigner zipalign -y
        echo $KEYSTORE | base64 -di > app/KEYSTORE.jks
        ./gradlew assembleRelease --no-daemon
        mv app/build/outputs/apk/release/app-release.apk .
        zipalign -v -p 4 app-release.apk radon.apk
        apksigner sign --ks-key-alias ${SIGNING_KEY_ALIAS} --ks-pass pass:${SIGNING_KEY_PASSWORD} --ks app/KEYSTORE.jks radon.apk   
    - uses: actions/upload-artifact@v3
      with:
        path: radon.apk
