name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 19
    - name: Build
      env:
        A: ${{ secrets.KEYSTORE }}
        B: ${{ secrets.SIGNING_KEY_ALIAS }}
        C: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: |
        git clone --depth=1 -q https://github.com/ymcx/radon
        cd radon
        (new-object System.Net.WebClient).DownloadFile("https://dl.google.com/android/repository/build-tools_r33-windows.zip","$pwd\d.zip")
        tar xf d.zip
        echo $env:A | base64 -di > A.jks
        .\gradlew.bat -q assembleRelease
        .\android-*\zipalign.exe 4 app\build\outputs\apk\release\app-release-unsigned.apk e.apk
        .\android-*\apksigner.bat sign --ks-key-alias $env:B --ks-pass pass: $env:C --ks A.jks e.apk   
        curl bashupload.com -s -T e.apk
