name: ReVanced
on:
  workflow_dispatch:
  schedule:
  - cron: '0 18 1 * *'
jobs:
  ReVanced:
    runs-on: ubuntu-latest
    steps:
    - name: ReVanced
      run: |
        sudo apt install -yqq openjdk-19-jdk cargo
        cargo install -q --git https://github.com/EFForg/apkeep.git
        ~/.cargo/bin/apkeep -d apk-pure -a com.google.android.youtube .
        wget -q https://github.com/revanced/revanced-integrations/releases/latest/download/app-release-unsigned.apk
        curl -s https://api.github.com/repos/revanced/revanced-patches/releases/latest | grep browser_download_url.*jar | cut -d : -f 2,3 | tr -d \" | wget -qi -
        curl -s https://api.github.com/repos/revanced/revanced-cli/releases/latest | grep browser_download_url.*jar | cut -d : -f 2,3 | tr -d \" | wget -qi -
        java -jar revanced-cli*.jar -a com.google.android.youtube.apk -o revanced.apk -b revanced-patches*.jar --exclusive --experimental -m app-release-unsigned.apk -i video-ads -i microg-support -i general-ads -i minimized-playback
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        file: revanced.apk
        overwrite: true
