name: ReVanced
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build APK
        run: |
          wget -q https://github.com/efforg/apkeep/releases/latest/download/apkeep-x86_64-unknown-linux-gnu
          chmod +x apkeep-x86_64-unknown-linux-gnu 
          ./apkeep-x86_64-unknown-linux-gnu -d apk-pure -a com.google.android.youtube .
          wget -q https://github.com/revanced/revanced-integrations/releases/latest/download/app-release-unsigned.apk
          curl -s https://api.github.com/repos/revanced/revanced-patches/releases/latest | grep browser_download_url.*jar | cut -d : -f 2,3 | tr -d \" | wget -qi -
          curl -s https://api.github.com/repos/revanced/revanced-cli/releases/latest | grep browser_download_url.*jar | cut -d : -f 2,3 | tr -d \" | wget -qi -
          java -jar revanced-cli*.jar -a com.google.android.youtube.apk -o revanced.apk -b revanced-patches*.jar --exclusive --experimental -m app-release-unsigned.apk -i video-ads -i microg-support -i general-ads -i minimized-playback
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: revanced.apk
          overwrite: true
