name: windowstest
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build
      env:
        a: ${{ secrets.KEYSTORE }}
        b: ${{ secrets.SECRETEST }}
      run: |
        echo ${b} | base64 -di
